on: push
name: deploy
jobs:
  deploy:
    name: deploy en eureka server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Usando github actions para eureka server - docker
        uses: msulccha/eureka-server@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_safe: true
          tags: ${{ github.sha }}
