on: push
name: deploy
jobs:
  deploy:
    name: deploy eureka server
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
      - name: Usando github actions para eureka server - docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_safe: true
          tags: ${{ github.sha }}